from pathlib import Path
import re

TODAY = "16. September 2026"
BASE = "https://brieflyletters.com"

STYLE = """:root{--bg:#f8f9fd;--text:#0f172a;--muted:#64748b;--accent:#6d5dfc;--line:#e8eaf2;--soft:#f2f0ff}*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,'Segoe UI',Roboto,Arial,sans-serif;color:var(--text);background:radial-gradient(850px 480px at 8% 0%,rgba(109,93,252,.15),transparent 60%),var(--bg);line-height:1.72}.wrap{max-width:1040px;margin:auto;padding:20px}.nav{display:flex;justify-content:space-between;padding:13px 17px;background:#ffffffd9;border-radius:20px}.brand,.back{color:var(--accent);font-weight:850;text-decoration:none}.hero,.article,.footer{max-width:820px;margin:auto}.hero{padding:58px 0 28px}.tag{padding:7px 11px;border-radius:999px;background:var(--soft);color:var(--accent);font-size:12px;font-weight:850}.hero h1{font-size:clamp(38px,6vw,58px);line-height:1.04;letter-spacing:-.05em;margin:17px 0 14px}.lead{font-size:19px;color:var(--muted)}.article{background:#fffffff0;border-radius:28px;padding:clamp(25px,5vw,50px);box-shadow:0 28px 80px #3730a31a}.box,.example{padding:18px 20px;border-radius:17px;background:#faf9ff;border:1px solid #e9e6ff}.section{padding:24px 0}.section+.section{border-top:1px solid var(--line)}h2{font-size:25px;margin:0 0 10px}h3{font-size:19px;margin:20px 0 8px}p,li{color:#334155}.cta{display:inline-block;padding:12px 17px;border-radius:12px;background:linear-gradient(135deg,#6d5dfc,#5146e5);color:#fff;text-decoration:none;font-weight:850}.links{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:32px}.links a{padding:14px;border:1px solid var(--line);border-radius:14px;text-decoration:none;color:var(--accent);font-weight:750}.source{font-size:13px;color:var(--muted)}.source a{color:var(--accent)}.fine,.footer{color:var(--muted);font-size:13px}.footer{margin-top:30px;padding:20px 4px;border-top:1px solid var(--line);display:flex;justify-content:space-between}.footer a{color:var(--muted);text-decoration:none;margin-left:14px}@media(max-width:620px){.links{grid-template-columns:1fr}.hero h1{font-size:38px}.footer{flex-direction:column}}"""

def page(title, desc, tag, h1, lead, body, related):
    return f'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{desc}"><meta name="robots" content="index, follow"><link rel="canonical" href="{BASE}/{related[0][0]}"><link rel="icon" type="image/x-icon" href="favicon.ico?v=5"><meta name="google-adsense-account" content="ca-pub-8272791832669756"><style>{STYLE}</style></head><body><div class="wrap"><nav class="nav"><a class="brand" href="index.html">Briefly ✨</a><a class="back" href="ratgeber.html">← Alle Ratgeber</a></nav><header class="hero"><span class="tag">{tag}</span><h1>{h1}</h1><p class="lead">{lead}</p></header><main class="article"><div class="box"><strong>Kurz gesagt:</strong> Diese Seite hilft beim Verstehen, Prüfen und Formulieren. Sie ersetzt keine individuelle Rechts- oder Sozialberatung. Prüfen Sie Fristen und Rechtsbehelfsinformationen immer im Originalschreiben.</div>{body}<section class="section"><h2>Mit Briefly weiterarbeiten</h2><p>Sie können den Text Ihres Schreibens in Briefly erklären lassen oder eine sachliche Antwort vorbereiten. Vergleichen Sie das Ergebnis anschließend mit dem Original und ergänzen Sie nur Angaben, die Sie selbst geprüft haben.</p><a class="cta" href="index.html#top">Briefly öffnen →</a></section><div class="links">{''.join(f'<a href="{href}">{label} →</a>' for href,label in related[1:])}</div><p class="fine">Aktualisiert: {TODAY}. Redaktioneller Inhalt von Briefly.</p></main><footer class="footer"><span>© 2026 Briefly</span><nav><a href="ueber-briefly.html">Über Briefly</a><a href="impressum.html">Impressum</a><a href="datenschutz.html">Datenschutz</a><a href="kontakt.html">Kontakt</a></nav></footer></div></body></html>'''

GUIDES = {
"jobcenter-bescheid-verstehen.html": page(
"Jobcenter-Bescheid verstehen: Betrag, Zeitraum & Widerspruch | Briefly",
"Jobcenter-Bescheid verständlich prüfen: Zeitraum, Berechnung, Bedarf, Einkommen, Rechtsbehelfsbelehrung und mögliche nächste Schritte einordnen.",
"JOBCENTER","Jobcenter-Bescheid verstehen","So lesen Sie einen Bescheid Schritt für Schritt und erkennen, welche Angaben Sie mit Ihren Unterlagen vergleichen sollten.",
'''<section class="section"><h2>Was ist bei einem Jobcenter-Bescheid zuerst wichtig?</h2><p>Ein Bescheid enthält eine Entscheidung zu Ihrem konkreten Vorgang. Prüfen Sie zuerst, für welchen Zeitraum er gilt, welche Personen berücksichtigt werden und welche Beträge genannt werden. Lesen Sie die Entscheidung nicht nur auf der ersten Seite: Berechnungsblätter und die Rechtsbehelfsbelehrung am Ende können für das Verständnis entscheidend sein.</p></section><section class="section"><h2>Diese Punkte sollten Sie vergleichen</h2><ul><li>Name, Bedarfsgemeinschaft und Zeitraum</li><li>bewilligte oder abgelehnte Leistung</li><li>berücksichtigtes Einkommen und mögliche Abzüge</li><li>Kosten für Unterkunft und Heizung, soweit aufgeführt</li><li>bereits bekannte Änderungen im Haushalt</li><li>Rechtsbehelfsbelehrung und dort genannte Frist</li></ul><p>Vergleichen Sie Zahlen mit Ihren eigenen Nachweisen. Eine Rückfrage beim Jobcenter kann beim Verständnis helfen, ersetzt aber nicht automatisch einen förmlichen Rechtsbehelf.</p></section><section class="section"><h2>Wenn ein Betrag unklar ist</h2><p>Markieren Sie genau die Zeile, die Sie nicht nachvollziehen können. Fragen Sie nicht nur „Warum ist der Bescheid falsch?“, sondern nennen Sie den konkreten Zeitraum oder Betrag.</p><div class="example"><p><strong>Beispiel:</strong> „Im Bescheid vom [Datum] wird für [Monat] ein Einkommen von [Betrag] berücksichtigt. Diesen Betrag kann ich meinen Unterlagen nicht zuordnen. Bitte erläutern Sie mir, aus welcher Angabe die Berechnung stammt.“</p></div></section><section class="section"><h2>Bescheid, Anhörung und Mitwirkung nicht verwechseln</h2><p>Bei einer Anhörung können Sie vor einer Entscheidung Stellung nehmen. Bei einer Mitwirkungsaufforderung werden meist Unterlagen oder Angaben verlangt. Ein Bescheid teilt dagegen eine Entscheidung mit. Deshalb braucht jedes Schreiben eine andere Reaktion.</p></section><section class="section"><h2>Häufige Fehler</h2><ul><li>nur den Auszahlungsbetrag ansehen und den Berechnungszeitraum übersehen</li><li>eine allgemeine Rückfrage bereits als Widerspruch betrachten</li><li>Fristen aus Internetbeispielen übernehmen statt aus der eigenen Rechtsbehelfsbelehrung</li><li>alte oder nicht passende Einkommensnachweise vergleichen</li></ul><p class="source">Offizielle Orientierung zu Bescheiden und Rechtsbehelfsbelehrung bietet auch die <a href="https://www.arbeitsagentur.de/arbeitslos-arbeit-finden/arbeitslosengeld/das-muessen-sie-beachten/arbeitslosengeld-bescheid" rel="noopener">Bundesagentur für Arbeit</a>.</p></section>''',
[("jobcenter-bescheid-verstehen.html",""),("jobcenter-briefe-verstehen.html","Jobcenter-Briefe im Überblick"),("jobcenter-anhoerung-verstehen.html","Anhörung verstehen"),("widerspruch-brief-struktur.html","Widerspruch strukturieren"),("brief-checkliste.html","Brief vor dem Versand prüfen")]),
"jobcenter-termin-verschieben.html": page(
"Jobcenter-Termin verschieben: höfliche Nachricht & Muster | Briefly",
"Jobcenter-Termin verschieben: Termin, Kundennummer, kurze Begründung und Bitte um Ersatztermin klar formulieren – mit Mustertext.",
"JOBCENTER","Jobcenter-Termin verschieben","Eine kurze, eindeutige Nachricht hilft dem Jobcenter, Ihren Termin schnell zuzuordnen und einen neuen Termin zu vereinbaren.",
'''<section class="section"><h2>Welche Angaben gehören in die Nachricht?</h2><ul><li>Datum und Uhrzeit des bestehenden Termins</li><li>Ihr Name</li><li>Kundennummer oder BG-Nummer, wenn im Schreiben genannt</li><li>kurze Mitteilung, dass Sie den Termin nicht wahrnehmen können</li><li>Bitte um einen neuen Termin</li></ul><p>Ein ausführlicher persönlicher Bericht ist meist nicht nötig. Entscheidend ist, dass klar erkennbar ist, welcher Termin betroffen ist.</p></section><section class="section"><h2>Muster für die Terminverschiebung</h2><div class="example"><p><strong>Betreff:</strong> Bitte um neuen Termin – Termin am [Datum]</p><p>Sehr geehrte Damen und Herren,</p><p>den für den [Datum] um [Uhrzeit] vereinbarten Termin kann ich leider nicht wahrnehmen. Ich bitte Sie um einen neuen Termin.</p><p>Kundennummer/BG-Nummer: [Nummer]</p><p>Bitte teilen Sie mir den Ersatztermin schriftlich mit.</p><p>Mit freundlichen Grüßen<br>[Name]</p></div></section><section class="section"><h2>Wenn Sie einen Grund nennen möchten</h2><p>Formulieren Sie knapp und wahrheitsgemäß. Schreiben Sie beispielsweise, dass Sie wegen eines bereits bestehenden Termins verhindert sind. Geben Sie sensible Details nur dann an, wenn sie wirklich erforderlich sind.</p></section><section class="section"><h2>Wichtig: auf die Bestätigung warten</h2><p>Gehen Sie nicht automatisch davon aus, dass der alte Termin aufgehoben wurde, nur weil Sie eine Nachricht gesendet haben. Prüfen Sie, ob Sie eine Bestätigung oder einen Ersatztermin erhalten. Bei kurzfristigen Änderungen kann ein zusätzlicher Kontakt über den im Einladungsschreiben angegebenen Weg sinnvoll sein.</p></section><section class="section"><h2>Häufige Fehler</h2><ul><li>Datum oder Uhrzeit des alten Termins nicht nennen</li><li>BG- oder Kundennummer vergessen, obwohl sie im Schreiben steht</li><li>einen Ersatztermin als bereits bestätigt behandeln</li><li>unnötig viele persönliche Informationen mitteilen</li></ul></section>''',
[("jobcenter-termin-verschieben.html",""),("termin-behoerde-verschieben.html","Behördentermin verschieben"),("jobcenter-briefe-verstehen.html","Jobcenter-Briefe verstehen"),("formelle-antwort-deutsch.html","Formelle Antwort schreiben"),("brief-checkliste.html","Brief-Checkliste")]),
"inkasso-brief-verstehen.html": page(
"Inkasso-Brief verstehen: Forderung, Kosten & nächste Schritte | Briefly",
"Inkasso-Brief erhalten? Forderung, Gläubiger, Hauptbetrag, Zusatzkosten und Fristen systematisch prüfen und eine sachliche Rückfrage vorbereiten.",
"INKASSO","Inkasso-Brief verstehen","Ein Inkassoschreiben kann Druck erzeugen. Prüfen Sie zuerst, worauf sich die Forderung bezieht, bevor Sie zahlen, widersprechen oder Unterlagen senden.",
'''<section class="section"><h2>Was sollten Sie zuerst prüfen?</h2><ul><li>Name des ursprünglichen Gläubigers</li><li>Vertrag, Bestellung oder Rechnung, auf die sich die Forderung bezieht</li><li>Hauptforderung und zusätzlich aufgeführte Kosten</li><li>bereits geleistete Zahlungen</li><li>Datum und Frist im Schreiben</li><li>Identität und Kontaktdaten des Inkassodienstleisters</li></ul><p>Wenn Ihnen die Forderung unbekannt ist, prüfen Sie sie zuerst anhand eigener Unterlagen. Überweisen Sie nicht allein deshalb, weil das Schreiben dringend formuliert ist.</p></section><section class="section"><h2>Wenn Sie die Forderung nicht zuordnen können</h2><div class="example"><p><strong>Beispiel für eine Rückfrage:</strong></p><p>„Ich kann die in Ihrem Schreiben vom [Datum] genannte Forderung derzeit nicht eindeutig zuordnen. Bitte nennen Sie mir den ursprünglichen Gläubiger, die zugrunde liegende Rechnung oder den Vertrag sowie eine nachvollziehbare Aufstellung des Gesamtbetrags.“</p></div><p>Eine solche Rückfrage entscheidet nicht automatisch, ob eine Forderung rechtlich besteht. Bei strittigen oder hohen Forderungen ist eine Verbraucher- oder Rechtsberatung sinnvoll.</p></section><section class="section"><h2>Hauptforderung und Zusatzkosten getrennt lesen</h2><p>Notieren Sie Hauptbetrag, Zinsen, Mahn- und Inkassokosten getrennt, soweit sie im Schreiben ausgewiesen sind. So können Sie gezielt nachfragen, wenn nur eine einzelne Position unklar ist.</p></section><section class="section"><h2>Inkassobrief oder gerichtliches Schreiben?</h2><p>Ein Schreiben eines Inkassobüros ist nicht dasselbe wie ein gerichtlicher Mahnbescheid. Prüfen Sie Absender und Dokumentbezeichnung genau. Bei einem gerichtlichen Schreiben müssen Sie die dort genannten Hinweise und Fristen gesondert beachten.</p></section><section class="section"><h2>Häufige Fehler</h2><ul><li>unter Zeitdruck zahlen, ohne die Forderung zuzuordnen</li><li>nur die Endsumme prüfen und die Einzelpositionen übersehen</li><li>sensible Unterlagen unaufgefordert vollständig versenden</li><li>ein gerichtliches Dokument wie eine normale Mahnung behandeln</li></ul><p class="source">Die <a href="https://www.verbraucherzentrale.de/inkasso-check-start" rel="noopener">Verbraucherzentrale</a> bietet einen kostenlosen Inkasso-Check zur ersten Einschätzung von Forderungen und Kosten.</p></section>''',
[("inkasso-brief-verstehen.html",""),("mahnung-verstehen.html","Mahnung verstehen"),("ratenzahlung-anfragen.html","Ratenzahlung anfragen"),("beschwerde-schreiben.html","Sachliche Beschwerde schreiben"),("brief-checkliste.html","Brief-Checkliste")]),
"rundfunkbeitrag-brief-verstehen.html": page(
"Rundfunkbeitrag-Brief verstehen: Zahlung, Bescheid & Befreiung | Briefly",
"Brief vom Beitragsservice verstehen: Zahlungsaufforderung, Einmalzahlungsaufforderung, Festsetzungsbescheid, Mahnung und Befreiung richtig einordnen.",
"BEHÖRDENPOST","Rundfunkbeitrag-Brief verstehen","Nicht jedes Schreiben des Beitragsservice bedeutet dasselbe. Entscheidend ist, ob es um Zahlungstermine, Rückstände, einen Festsetzungsbescheid oder einen Antrag geht.",
'''<section class="section"><h2>Welche Art von Schreiben haben Sie erhalten?</h2><h3>Zahlungs- oder Einmalzahlungsaufforderung</h3><p>Bei Überweisung informiert der Beitragsservice über Betrag und Fälligkeit. Seit 2025 wird schrittweise auf eine Einmalzahlungsaufforderung umgestellt: Sie nennt wiederkehrende Zahlungstermine, ohne dass vor jedem Termin ein neues Schreiben verschickt wird.</p><h3>Festsetzungsbescheid</h3><p>Bei Zahlungsrückständen kann ein Festsetzungsbescheid folgen. Prüfen Sie Zeitraum, Betrag, Beitragsnummer und die Rechtsbehelfsbelehrung im Original.</p><h3>Mahnung</h3><p>Eine Mahnung kann auf bereits festgesetzte Rückstände folgen. Vergleichen Sie den genannten Betrag mit früheren Bescheiden und eigenen Zahlungen.</p></section><section class="section"><h2>Diese Angaben sollten Sie markieren</h2><ul><li>9-stellige Beitragsnummer</li><li>betroffener Zeitraum</li><li>genannte Zahlungstermine</li><li>offener Betrag</li><li>bereits geleistete Zahlungen</li><li>Hinweise zu Widerspruch, Befreiung oder Ermäßigung</li></ul></section><section class="section"><h2>Wenn Sie bereits gezahlt haben</h2><p>Vergleichen Sie Zahlungsdatum, Betrag und Beitragsnummer mit dem Schreiben. Als Zahlungsnachweis nennt der Beitragsservice den Kontoauszug. Übermitteln Sie nur den für die Klärung nötigen Ausschnitt und nutzen Sie den offiziellen Kontaktweg.</p></section><section class="section"><h2>Befreiung wird nicht automatisch erteilt</h2><p>Wer die Voraussetzungen für eine Befreiung oder Ermäßigung erfüllt, muss diese beantragen und entsprechende Nachweise einreichen. Prüfen Sie den bewilligten Zeitraum und verlassen Sie sich nicht darauf, dass eine Befreiung automatisch verlängert wird.</p></section><section class="section"><h2>Häufige Fehler</h2><ul><li>eine Einmalzahlungsaufforderung wie eine einmalige Rechnung behandeln</li><li>Beitragsnummer bei einer Überweisung falsch oder gar nicht angeben</li><li>eine Befreiung als automatisch voraussetzen</li><li>bei einem Festsetzungsbescheid die Rechtsbehelfsbelehrung übersehen</li></ul><p class="source">Aktuelle Informationen finden Sie direkt beim <a href="https://www.rundfunkbeitrag.de/zahlung" rel="noopener">Beitragsservice</a> sowie auf der Seite zur <a href="https://www.rundfunkbeitrag.de/einmalzahlungsaufforderung" rel="noopener">Einmalzahlungsaufforderung</a>.</p></section>''',
[("rundfunkbeitrag-brief-verstehen.html",""),("behoerdenbriefe-verstehen.html","Behördenbriefe verstehen"),("mahnung-verstehen.html","Mahnung verstehen"),("ratenzahlung-anfragen.html","Ratenzahlung anfragen"),("brief-checkliste.html","Brief-Checkliste")]),
}

created=[]
for name, html in GUIDES.items():
    p=Path(name)
    if not p.exists():
        p.write_text(html, encoding="utf-8")
        created.append(name)
        print("Created:", name)

hub=Path("ratgeber.html")
text=hub.read_text(encoding="utf-8")
cards=[
('jobcenter','jobcenter-bescheid-verstehen.html','Jobcenter-Bescheid verstehen','Betrag, Zeitraum, Berechnung und Rechtsbehelfsbelehrung systematisch prüfen.'),
('jobcenter','jobcenter-termin-verschieben.html','Jobcenter-Termin verschieben','Eine kurze Nachricht mit Termin, Kundennummer und Bitte um Ersatztermin formulieren.'),
('schreiben','inkasso-brief-verstehen.html','Inkasso-Brief verstehen','Forderung, ursprünglichen Gläubiger, Kosten und Fristen geordnet prüfen.'),
('behoerden','rundfunkbeitrag-brief-verstehen.html','Rundfunkbeitrag-Brief verstehen','Zahlungsaufforderung, Festsetzungsbescheid, Mahnung und Befreiung unterscheiden.'),
]
new_cards=''
for cat,href,title,desc in cards:
    if f'href="{href}"' not in text:
        new_cards += f'<a class="card" data-cat="{cat}" href="{href}"><span>{"Jobcenter" if cat=="jobcenter" else "Schreiben" if cat=="schreiben" else "Behörden"}</span><h2>{title}</h2><p>{desc}</p><div class="read">Ratgeber lesen →</div></a>\n'
if new_cards:
    text=text.replace('</main>',new_cards+'</main>',1)
text=re.sub(r'<span id="count">\d+ Ratgeber</span>','<span id="count">32 Ratgeber</span>',text,count=1)
hub.write_text(text,encoding="utf-8")

# Add direct internal links from strong related guides.
links={
'jobcenter-briefe-verstehen.html': '<p><a href="jobcenter-bescheid-verstehen.html">Jobcenter-Bescheid Schritt für Schritt prüfen →</a> · <a href="jobcenter-termin-verschieben.html">Jobcenter-Termin verschieben →</a></p>',
'mahnung-verstehen.html': '<p><a href="inkasso-brief-verstehen.html">Inkasso-Brief verstehen →</a></p>',
'behoerdenbriefe-verstehen.html': '<p><a href="rundfunkbeitrag-brief-verstehen.html">Rundfunkbeitrag-Brief verstehen →</a></p>',
}
for name, block in links.items():
    p=Path(name)
    if p.exists():
        t=p.read_text(encoding="utf-8")
        marker=block.split('href="',1)[1].split('"',1)[0]
        if marker not in t and '</main>' in t:
            t=t.replace('</main>',f'<section><h2>Weitere passende Hilfe</h2>{block}</section></main>',1)
            p.write_text(t,encoding="utf-8")
            print("Linked from:",name)

print(f"Created {len(created)} new search guides")